function[] = writePSMTemplate
%% writePSMTemplate  Write reST markup for the PSM.template file
% ----------
%   writePSMTemplate
%   Writes a rst file for PSM.template. Since the template is not
%   functional code, it cannot be processed by the reST parsers. Instead,
%   this markup file needs to be written directly.
% ----------

% Get the RST
newlin = string(newline);
rst = strcat(...
    'Template', newlin,...
    '========', newlin,...
    "The template file provides a how-to and template for developing new PSM ",...
    'classes. To use the template enter:',    newlin,...
    newlin,...
    '::',    newlin,...
    newlin,...
    "    edit PSM.template", newlin,...
    newlin,...
    'in the Matlab console and follow the prompts in the file.', newlin);

% Write the file
newFile = "PSM/template.rst";
fid = fopen(newFile, 'w');
closeFile = onCleanup( @()fclose(fid) );
fprintf(fid, '%s', rst);

end


