function[] = tests
%% dash.is.tests  Implement unit tests for the dash.is subpackage
% ----------
%   dash.is.tests
%   Runs the units tests. If the tests pass, exits silently.
%   If the tests fail, prints the first failed test to the console.
% ----------
%   Tests the following functions: strflag, strlist


%% strflag

% Build test values
strScalar = "test";
charRow = 'test';

tests = {...
    "test", true, "string scalar";...
    'test', true, 'character row vector';...
    [strScalar, strScalar], false, "string vector";...
    charRow', false, "char column";...
    [charRow;charRow], false, "char matrix";...
    [], false, "empty";...
    5, false, "numeric";...
    true, false, "logical true";...
    false, false, "logical false"
    };

% Test each value
nTests = size(tests, 1);
for t = 1:nTests
    assert( dash.is.strflag(tests{t,1}) == tests{t,2}, "strflag: %s", tests{t,3} );
end


%% strlist

strRow = ["test1", "test2"];
cellstrRow = {'test1','test2'};

tests = {...
    strRow, true, "string row vector";...
    strRow', true, "string column vector";...
    charRow, true, "character row vector";...
    cellstrRow(1), true, 'cellstr scalar';...
    cellstrRow, true, 'cellstr row';...
    cellstrRow', true, 'cellstr column';...
    ...
    [strRow;strRow], false, "string matrix";...
    [cellstrRow;cellstrRow], false, "cellstr matrix";...
    charRow', false, "character column vector";...
    [charRow;charRow], false, "character matrix";...
    cat(3, charRow, charRow), false, 'char array';...
    ...
    [], false, 'empty';...
    5, false, 'numeric';...
    true, false, 'logical true';...
    false, false, 'logical false';
    };

for t = 1:size(tests,1)
    assert( dash.is.strlist(tests{t,1}) == tests{t,2}, "strlist: %s", tests{t,3} );
end

end
