function[T] = info
%% Lists available PSMs along with a brief description
%
% T = PSM.info
% Returns a list of available PSMs and their descriptions as a table

% Get the list of PSMs and their descriptions
psms = [...
    "bayfox", "A Bayesian model for d18Oc of planktic foraminifera";...
    "baymag", "A Bayesian model for Mg/Ca of planktic foraminifera";...
    "bayspar", "A Bayesian model for TEX86";...
    "bayspline", "Baysian model for UK'37";...
    "linear", "General linear PSM of form: Y = a1*X1 + a2*X2 + ... an*Xn + b";...
    "prysmCellulose", "The cellulose sensor module from the PRYSM Python package";...
    "prysmCoral", "The coral sensor module from the PRYSM Python package";...
    "prysmIcecore", "The ice-core sensor module from the PRYSM Python package";...
    "prysmSpeleothem", "The speleothem sensor module from the PRYSM Python package";...
    "vslite", "The Vaganov-Shaskin Lite (VS-Lite) tree ring model";...
    ];

% Create a table
T = table(psms(:,1), psms(:,2), 'VariableNames', ["PSM","Description"]);

end