function[rst] = packageTitle(title, h1, details)

% Get components
underline = repmat("=", [1 strlength(title)]);
details = strjoin([h1;details], "\n\n");

% Format
rst = strcat(...
    title,     "\n",...
    underline, '\n',...
    details,   '\n',...
               '\n',...
               '\n'...
    );

end