function[m] = ensFileCheck( file, type )

if ~ismember( type, ["new","load","add"])
    error('Unrecognized type');
end

% String
if ~isstrflag(file)
    error('The file name must be a string.');
end

% .ens extension
file = char(file);
if length(file)<5 || ~strcmp( file(end-3:end), '.ens' )
    error('The file name must end with a .ens extension.');
end

% New file should not already be on path
if strcmp(type, 'new') && exist( file, 'file' )
    error('The file %s already exists. Use the function "addEnsemble.m" or delete the pre-existing .ens file.', file);
end

% Existing file should be on path
if ismember( type, ["add","load"] ) && ~exist(file, 'file')
    error('The file %s does not exist. It may be mispelled or not on the active path.', file);
end 
    
% Load the appropriate type of matfile
if ismember( type, ["new", "add"] )
    m = matfile( file, 'Writable', true );
else   % Only need a readable matfile if loading
    m = matfile( file );
end

% If a pre-existing file, check for fields and completion
if ismember(type, ["add","load"])
    
    fields = who(m);
    if ~ismember( 'complete', fields )
        error('The %s file is missing the "complete" field. The file may not have been generated by "buildEnsemble.m".', file);
    end
    
    % Check for completion
    if ~m.complete
        error('The ensemble in the %s file was not successfully built. Try re-building using "buildEnsemble.m".', file);
    end
    
    % Check the remaining fields
    if ~ismember( 'M', fields )
        error('The %s file is missing the "M" field.', file);
    elseif ~ismember( 'design', fields )
        error('The %s file is missing the "design" field.', file);
    elseif ~ismember( 'ensSize', fields )
        error('The %s file is missing the "ensSize" field.', file);
    end 
end

end